# Generated by Django 5.2.3 on 2025-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simblissimaApp', '0003_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], max_length=20, null=True),
        ),
    ]
